/**
 * Model Inference Module for LightGBM Meal Ranker
 * 
 * Purpose:
 *     This module provides real-time meal ranking using the trained LightGBM model.
 *     It loads the model at server startup and generates predictions for candidate meals.
 * 
 * Key Responsibilities:
 *     - Load meal_ranker.txt model file at server startup (one-time)
 *     - Load and validate feature_schema.json
 *     - Fetch user profile and meal logs from Supabase
 *     - Compute user's remaining macros (targets - consumed today)
 *     - Query candidate meals from the meals table
 *     - Engineer features for each (user, meal) pair matching training schema:
 *         * macro_delta_calories: |meal.calories - remaining.calories|
 *         * macro_delta_protein: |meal.protein - remaining.protein|
 *         * macro_delta_carbs: |meal.carbs - remaining.carbs|
 *         * macro_delta_fat: |meal.fat - remaining.fat|
 *         * cuisine_match: 1 if meal.cuisine == user.cuisine_pref else 0
 *         * meal_slot_match: 1 if meal.slot == requested_slot else 0
 *         * days_since_last_eaten: days since user last logged meal (999 if never)
 *     - Run model inference to score all candidate meals
 *     - Rank meals by predicted score (descending)
 *     - Return top 5 recommendations
 *     - Fall back to heuristic ranker if model fails
 * 
 * Dependencies:
 *     - lightgbm (Node.js bindings) OR onnxruntime-node (recommended)
 *     - @supabase/supabase-js: For database queries
 * 
 * Expected Input:
 *     - meal_ranker.txt: Trained model file
 *     - feature_schema.json: Feature validation schema
 *     - User ID, meal type, profile data, remaining macros
 * 
 * Expected Output:
 *     - Array of top 5 MealSuggestion objects matching existing API contract
 * 
 * Usage:
 *     import { rankMeals } from '@/lib/meal-recommender/inference';
 *     const recommendations = await rankMeals(userId, mealType, profileData, remainingMacros);
 * 
 * Author: Generated by Kiro AI
 * Date: 2024
 */

import fs from 'fs';
import path from 'path';

/**
 * Feature schema structure defining expected feature vector format
 */
interface FeatureSchema {
  version: string;
  feature_count: number;
  features: Array<{
    name: string;
    type: string;
    min: number;
    max: number;
  }>;
}

/**
 * Model state singleton
 */
interface ModelState {
  model: string | null; // Model file contents (LightGBM text format)
  schema: FeatureSchema | null;
  isLoaded: boolean;
  useFallback: boolean; // Flag indicating whether to use fallback ranking
  loadError: string | null;
}

// Singleton state for the loaded model
const modelState: ModelState = {
  model: null,
  schema: null,
  isLoaded: false,
  useFallback: false,
  loadError: null
};

/**
 * Load the feature schema from feature_schema.json
 * 
 * @returns The loaded feature schema or null on error
 */
function loadFeatureSchema(): FeatureSchema | null {
  try {
    const schemaPath = path.join(process.cwd(), 'lib', 'meal-recommender', 'feature_schema.json');
    
    if (!fs.existsSync(schemaPath)) {
      console.error(`[Model Loader] Feature schema not found at: ${schemaPath}`);
      return null;
    }

    const schemaContent = fs.readFileSync(schemaPath, 'utf-8');
    const schema = JSON.parse(schemaContent) as FeatureSchema;
    
    console.log(`[Model Loader] Feature schema loaded successfully (version: ${schema.version}, features: ${schema.feature_count})`);
    return schema;
  } catch (error) {
    console.error('[Model Loader] Error loading feature schema:', error);
    return null;
  }
}

/**
 * Validate the feature schema structure
 * 
 * Checks:
 * - Feature count is 7 (as per training specification)
 * - Feature names match expected schema
 * - Feature order is correct
 * 
 * @param schema - The feature schema to validate
 * @returns true if schema is valid, false otherwise
 */
function validateSchema(schema: FeatureSchema): boolean {
  try {
    // Check feature count
    if (schema.feature_count !== 7) {
      console.error(`[Model Loader] Invalid feature count: expected 7, got ${schema.feature_count}`);
      return false;
    }

    if (!schema.features || schema.features.length !== 7) {
      console.error(`[Model Loader] Invalid features array length: expected 7, got ${schema.features?.length || 0}`);
      return false;
    }

    // Expected feature names in order
    const expectedFeatures = [
      'macro_delta_calories',
      'macro_delta_protein',
      'macro_delta_carbs',
      'macro_delta_fat',
      'cuisine_match',
      'meal_slot_match',
      'days_since_last_eaten'
    ];

    // Validate feature names and order
    for (let i = 0; i < expectedFeatures.length; i++) {
      if (schema.features[i].name !== expectedFeatures[i]) {
        console.error(
          `[Model Loader] Feature mismatch at index ${i}: expected '${expectedFeatures[i]}', got '${schema.features[i].name}'`
        );
        return false;
      }
    }

    console.log('[Model Loader] Feature schema validation passed');
    return true;
  } catch (error) {
    console.error('[Model Loader] Error during schema validation:', error);
    return false;
  }
}

/**
 * Load the trained LightGBM model from meal_ranker.txt
 * 
 * This function reads the serialized model file. The actual inference
 * will be implemented in a separate function using either:
 * - ONNX runtime (recommended for compatibility)
 * - LightGBM Node.js bindings
 * - Custom tree traversal implementation
 * 
 * @returns The model content as string, or null on error
 */
function loadModel(): string | null {
  try {
    const modelPath = path.join(process.cwd(), 'lib', 'meal-recommender', 'meal_ranker.txt');
    
    if (!fs.existsSync(modelPath)) {
      console.error(`[Model Loader] Model file not found at: ${modelPath}`);
      return null;
    }

    const modelContent = fs.readFileSync(modelPath, 'utf-8');
    
    // Basic validation - check if it looks like a LightGBM model
    if (!modelContent.includes('tree') || !modelContent.includes('num_class')) {
      console.error('[Model Loader] Model file does not appear to be a valid LightGBM model');
      return null;
    }

    console.log('[Model Loader] Model file loaded successfully');
    return modelContent;
  } catch (error) {
    console.error('[Model Loader] Error loading model file:', error);
    return null;
  }
}

/**
 * Initialize the model at server startup
 * 
 * This function:
 * 1. Loads the feature schema and validates it
 * 2. Loads the trained model file
 * 3. Sets appropriate flags for fallback behavior if loading fails
 * 
 * Error handling strategy:
 * - If model or schema fails to load, log error and set useFallback=true
 * - Server continues to function using heuristic ranking
 * - Does not throw exceptions to prevent server crashes
 */
function initializeModel(): void {
  console.log('[Model Loader] Starting model initialization...');

  try {
    // Load and validate feature schema
    const schema = loadFeatureSchema();
    if (!schema) {
      modelState.loadError = 'Failed to load feature schema';
      modelState.useFallback = true;
      console.error('[Model Loader] Model initialization failed: schema loading error');
      return;
    }

    if (!validateSchema(schema)) {
      modelState.loadError = 'Feature schema validation failed';
      modelState.useFallback = true;
      console.error('[Model Loader] Model initialization failed: schema validation error');
      return;
    }

    modelState.schema = schema;

    // Load model file
    const model = loadModel();
    if (!model) {
      modelState.loadError = 'Failed to load model file';
      modelState.useFallback = true;
      console.error('[Model Loader] Model initialization failed: model loading error');
      return;
    }

    modelState.model = model;
    modelState.isLoaded = true;
    modelState.useFallback = false;
    
    console.log('[Model Loader] ✓ Model initialization completed successfully');
    console.log('[Model Loader] Note: Model inference engine (ONNX/LightGBM) needs to be configured for predictions');
  } catch (error) {
    modelState.loadError = error instanceof Error ? error.message : 'Unknown error';
    modelState.useFallback = true;
    console.error('[Model Loader] Unexpected error during model initialization:', error);
  }
}

/**
 * Get the current model state
 * 
 * @returns The current model state including loaded status and fallback flag
 */
export function getModelState(): Readonly<ModelState> {
  return { ...modelState };
}

/**
 * Get the loaded feature schema
 * 
 * @returns The feature schema if loaded, null otherwise
 */
export function getFeatureSchema(): FeatureSchema | null {
  return modelState.schema;
}

/**
 * Check if the model is loaded and ready for inference
 * 
 * @returns true if model is loaded, false if fallback should be used
 */
export function isModelReady(): boolean {
  return modelState.isLoaded && !modelState.useFallback;
}

// Initialize model at module load time (top-level)
// This runs once when the module is first imported by the server
initializeModel();

// =============================================================================
// Feature Engineering for Inference
// =============================================================================

/**
 * Type definitions for feature engineering
 */

interface Meal {
  id: string;
  name: string;
  description?: string;
  cuisine_type: string;
  meal_slot: string;
  calories: number;
  protein_g: number;
  carbs_g: number;
  fat_g: number;
  ingredients?: string[];
}

interface RemainingMacros {
  calories: number;
  protein_g: number;
  carbs_g: number;
  fat_g: number;
}

interface UserProfile {
  cuisine_preference?: string | null;
}

/**
 * Compute macro delta features: absolute difference between meal and remaining macros.
 * 
 * MIRRORS: train.py → compute_macro_delta()
 * 
 * This is the PRIMARY feature for meal ranking. It captures how well a meal "fits"
 * the user's remaining nutritional needs for the day.
 * 
 * Rationale:
 * - Small deltas = meal closely matches remaining needs (GOOD fit)
 * - Large deltas = meal overshoots or undershoots needs (POOR fit)
 * - Absolute values ensure we penalize both overshooting and undershooting
 * 
 * Example:
 * - User has 500 calories remaining
 * - Meal A: 480 calories → delta = 20 (excellent fit)
 * - Meal B: 800 calories → delta = 300 (poor fit, too much)
 * - Meal C: 200 calories → delta = 300 (poor fit, too little)
 * 
 * @param meal - Meal object with nutritional information
 * @param remaining - Remaining macros for the user today
 * @returns Array of 4 floats: [|calories_delta|, |protein_delta|, |carbs_delta|, |fat_delta|]
 */
export function computeMacroDelta(meal: Meal, remaining: RemainingMacros): number[] {
  // Compute absolute difference for each macro nutrient
  // This penalizes both eating too much and too little
  const caloriesDelta = Math.abs(meal.calories - remaining.calories);
  const proteinDelta = Math.abs(meal.protein_g - remaining.protein_g);
  const carbsDelta = Math.abs(meal.carbs_g - remaining.carbs_g);
  const fatDelta = Math.abs(meal.fat_g - remaining.fat_g);
  
  return [
    caloriesDelta,
    proteinDelta,
    carbsDelta,
    fatDelta
  ];
}

/**
 * Compute cuisine match feature: 1 if meal cuisine matches user preference, else 0.
 * 
 * MIRRORS: train.py → compute_cuisine_match()
 * 
 * Rationale:
 * - Users are more likely to enjoy and accept meals from their preferred cuisine
 * - This is a simple binary preference signal
 * - If user has no preference (null/undefined), all meals get 0 (no boost)
 * 
 * Example:
 * - User prefers "italian"
 * - Meal A: cuisine="italian" → match = 1 (boosted)
 * - Meal B: cuisine="mexican" → match = 0 (not boosted)
 * - Meal C: cuisine="italian" → match = 1 (boosted)
 * 
 * @param meal - Meal object with cuisine_type
 * @param userPreference - User's preferred cuisine type (or null/undefined for no preference)
 * @returns 1 if match, 0 if no match or no preference
 */
export function computeCuisineMatch(meal: Meal, userPreference: string | null | undefined): number {
  // If user has no preference, return 0 (no boost)
  if (!userPreference) {
    return 0;
  }
  
  // Check if meal's cuisine matches user's preference (case-insensitive)
  const mealCuisine = meal.cuisine_type?.toLowerCase() || '';
  const userPrefLower = userPreference.toLowerCase();
  
  return mealCuisine === userPrefLower ? 1 : 0;
}

/**
 * Compute meal slot match feature: 1 if meal fits requested slot, else 0.
 * 
 * MIRRORS: train.py → compute_meal_slot_match()
 * 
 * Rationale:
 * - Meals are categorized as breakfast, lunch, dinner, or snack
 * - Users request meals for specific slots (e.g., "I need breakfast")
 * - Matching the slot ensures appropriate meals (no dinner for breakfast)
 * - This is a HARD constraint feature - mismatches should be heavily penalized
 * 
 * Example:
 * - User requests "breakfast"
 * - Meal A: meal_slot="breakfast" → match = 1 (appropriate)
 * - Meal B: meal_slot="dinner" → match = 0 (inappropriate, too heavy)
 * - Meal C: meal_slot="snack" → match = 0 (inappropriate, too light)
 * 
 * @param meal - Meal object with meal_slot
 * @param requestedSlot - The meal slot being requested by the user
 * @returns 1 if match, 0 if no match
 */
export function computeMealSlotMatch(meal: Meal, requestedSlot: string): number {
  // Check if meal's slot matches the requested slot (case-insensitive)
  const mealSlot = meal.meal_slot?.toLowerCase() || '';
  const requestedSlotLower = requestedSlot.toLowerCase();
  
  return mealSlot === requestedSlotLower ? 1 : 0;
}

/**
 * Compute days since user last ate this meal (recency feature).
 * 
 * MIRRORS: train.py → compute_days_since_last_eaten()
 * 
 * Rationale:
 * - Users want VARIETY in their meal recommendations
 * - Recently eaten meals should be deprioritized (avoid repetition)
 * - Never-eaten meals should be boosted (encourage exploration)
 * - Use 999 as default for never-eaten to strongly boost new meals
 * 
 * Example:
 * - Today is Day 100
 * - Meal A: last eaten Day 98 → recency = 2 days (very recent, penalize)
 * - Meal B: last eaten Day 85 → recency = 15 days (moderate, neutral)
 * - Meal C: never eaten → recency = 999 days (boost exploration)
 * 
 * Implementation:
 * - Queries meal_logs table for this meal_name and user_id
 * - Calculates days between today and most recent log
 * - Returns 999 if meal never logged by this user
 * 
 * @param mealId - Meal identifier (matches meal name in meal_logs)
 * @param userId - User identifier
 * @param supabase - Supabase client for database queries
 * @returns Promise<number> - Days since last eaten (999 if never eaten)
 */
export async function computeDaysSinceLastEaten(
  mealId: string,
  userId: string,
  supabase: any
): Promise<number> {
  try {
    // Query meal_logs for the most recent log of this meal by this user
    // We match on meal_name since meal_logs doesn't have a meal_id foreign key
    const { data, error } = await supabase
      .from('meal_logs')
      .select('logged_at')
      .eq('user_id', userId)
      .eq('meal_name', mealId)
      .order('logged_at', { ascending: false })
      .limit(1);
    
    if (error) {
      console.error('[Feature Engineering] Error querying meal_logs:', error);
      return 999; // Default to never eaten on error
    }
    
    if (!data || data.length === 0) {
      // Meal never logged by this user
      return 999;
    }
    
    // Calculate days since last eaten
    const lastEatenDate = new Date(data[0].logged_at);
    const today = new Date();
    const diffMs = today.getTime() - lastEatenDate.getTime();
    const daysSince = Math.floor(diffMs / (1000 * 60 * 60 * 24));
    
    return daysSince;
  } catch (error) {
    console.error('[Feature Engineering] Exception in computeDaysSinceLastEaten:', error);
    return 999; // Default to never eaten on exception
  }
}

/**
 * Compute complete 7-feature vector for a (user, meal) pair.
 * 
 * MIRRORS: train.py → engineer_features()
 * 
 * This is the MAIN feature engineering function that combines all individual
 * features into the final input vector for the LightGBM model.
 * 
 * Feature Vector (7 elements in this exact order):
 * 1. macro_delta_calories: |meal.calories - remaining.calories|
 * 2. macro_delta_protein: |meal.protein_g - remaining.protein_g|
 * 3. macro_delta_carbs: |meal.carbs_g - remaining.carbs_g|
 * 4. macro_delta_fat: |meal.fat_g - remaining.fat_g|
 * 5. cuisine_match: 1 if meal.cuisine matches user.cuisine_preference else 0
 * 6. meal_slot_match: 1 if meal.meal_slot matches requested_slot else 0
 * 7. days_since_last_eaten: days since user ate this meal (999 if never)
 * 
 * Feature Rationale:
 * - Features 1-4 (macro deltas): Capture nutritional fit quality
 * - Feature 5 (cuisine): Captures user taste preference
 * - Feature 6 (meal slot): Ensures meal appropriateness for time of day
 * - Feature 7 (recency): Encourages variety and exploration
 * 
 * Example:
 * User wants breakfast, prefers Italian, has 400 cal/30g protein/40g carbs/15g fat remaining
 * 
 * Meal A: Italian breakfast, 380 cal/28g protein/38g carbs/14g fat, eaten 5 days ago
 * → [20, 2, 2, 1, 1, 1, 5] (excellent fit - all features align)
 * 
 * Meal B: Mexican dinner, 700 cal/50g protein/60g carbs/25g fat, never eaten
 * → [300, 20, 20, 10, 0, 0, 999] (poor fit - wrong slot, too much food)
 * 
 * @param profile - User profile with cuisine_preference
 * @param meal - Meal object with nutritional info and metadata
 * @param remaining - Remaining macros for the user
 * @param userId - User ID for recency calculation
 * @param requestedSlot - Meal slot being requested (breakfast/lunch/dinner/snack)
 * @param supabase - Supabase client for database queries
 * @returns Promise<number[]> - 7-element feature vector
 */
export async function computeFeatures(
  profile: UserProfile,
  meal: Meal,
  remaining: RemainingMacros,
  userId: string,
  requestedSlot: string,
  supabase: any
): Promise<number[]> {
  // Feature 1-4: Macro delta features (nutritional fit)
  // TRAINING MAPPING: train.py lines 350-365
  const macroDeltas = computeMacroDelta(meal, remaining);
  
  // Feature 5: Cuisine match (taste preference)
  // TRAINING MAPPING: train.py lines 368-395
  const cuisineMatch = computeCuisineMatch(meal, profile.cuisine_preference);
  
  // Feature 6: Meal slot match (appropriateness for time of day)
  // TRAINING MAPPING: train.py lines 398-425
  const mealSlotMatch = computeMealSlotMatch(meal, requestedSlot);
  
  // Feature 7: Recency (variety and exploration)
  // TRAINING MAPPING: train.py lines 428-465
  const daysSince = await computeDaysSinceLastEaten(meal.name, userId, supabase);
  
  // Combine all features into final 7-element vector
  // ORDER MATTERS - this must match the training schema
  const featureVector = [
    macroDeltas[0],  // macro_delta_calories
    macroDeltas[1],  // macro_delta_protein
    macroDeltas[2],  // macro_delta_carbs
    macroDeltas[3],  // macro_delta_fat
    cuisineMatch,    // cuisine_match
    mealSlotMatch,   // meal_slot_match
    daysSince        // days_since_last_eaten
  ];
  
  return featureVector;
}

/**
 * Validate feature vector against schema.
 * 
 * Checks:
 * - Feature vector has correct length (7 elements)
 * - All values are numbers (not NaN, null, or undefined)
 * - All values are finite (not Infinity or -Infinity)
 * - Values are within expected ranges (optional, based on schema)
 * 
 * This prevents train-serve skew by ensuring inference features match training format.
 * 
 * @param features - Feature vector to validate
 * @param schema - Feature schema defining expected format
 * @returns true if valid, false if validation fails
 */
export function validateFeatureVector(features: number[], schema: FeatureSchema | null): boolean {
  try {
    // Check schema is loaded
    if (!schema) {
      console.error('[Feature Validation] No schema loaded');
      return false;
    }
    
    // Check feature count matches schema
    if (features.length !== schema.feature_count) {
      console.error(
        `[Feature Validation] Feature count mismatch: expected ${schema.feature_count}, got ${features.length}`
      );
      return false;
    }
    
    // Check all values are valid numbers
    for (let i = 0; i < features.length; i++) {
      const value = features[i];
      const featureDef = schema.features[i];
      
      // Check if value is a valid number
      if (typeof value !== 'number' || !isFinite(value)) {
        console.error(
          `[Feature Validation] Invalid value at index ${i} (${featureDef.name}): ${value}`
        );
        return false;
      }
      
      // Optional: Check if value is within expected range
      // This is a soft check - we log warnings but don't fail validation
      if (value < featureDef.min || value > featureDef.max) {
        console.warn(
          `[Feature Validation] Value out of expected range at index ${i} (${featureDef.name}): ` +
          `${value} (expected ${featureDef.min}-${featureDef.max})`
        );
        // Don't fail validation for range issues - they may occur in production
      }
    }
    
    return true;
  } catch (error) {
    console.error('[Feature Validation] Exception during validation:', error);
    return false;
  }
}

// =============================================================================
// Model Inference and Ranking
// =============================================================================

/**
 * Run model inference on feature vectors to predict scores.
 * 
 * MIRRORS: LightGBM model prediction in train.py
 * 
 * This function runs the trained LightGBM model on an array of feature vectors
 * and returns predicted scores for each meal candidate.
 * 
 * Implementation options:
 * 1. ONNX Runtime (recommended): Export model to ONNX format, use onnxruntime-node
 * 2. LightGBM Node.js bindings: Use native LightGBM library (if available)
 * 3. Custom tree traversal: Parse model.txt and implement prediction logic
 * 
 * Current status: PLACEHOLDER - needs actual inference engine configured
 * 
 * Rationale:
 * - Batch prediction is more efficient than one-by-one
 * - Returns float scores where higher = better meal fit
 * - Scores can be any range (will be sorted relatively)
 * 
 * @param featureVectors - Array of 7-element feature vectors (one per meal)
 * @returns Array of predicted scores (one per meal)
 * @throws Error if model inference fails
 */
export function predictScores(featureVectors: number[][]): number[] {
  // Validate inputs
  if (!featureVectors || featureVectors.length === 0) {
    throw new Error('[Model Inference] Empty feature vectors array');
  }
  
  // Validate model is loaded
  if (!modelState.isLoaded || !modelState.model) {
    throw new Error('[Model Inference] Model not loaded');
  }
  
  // Validate all feature vectors have correct length
  const expectedLength = modelState.schema?.feature_count || 7;
  for (let i = 0; i < featureVectors.length; i++) {
    if (featureVectors[i].length !== expectedLength) {
      throw new Error(
        `[Model Inference] Invalid feature vector at index ${i}: ` +
        `expected ${expectedLength} features, got ${featureVectors[i].length}`
      );
    }
  }
  
  // TODO: Implement actual model inference
  // This is a placeholder that will be replaced when ONNX/LightGBM is configured
  // 
  // ONNX approach:
  // const session = await ort.InferenceSession.create(modelPath);
  // const tensor = new ort.Tensor('float32', featureVectors.flat(), [featureVectors.length, 7]);
  // const results = await session.run({ input: tensor });
  // return Array.from(results.output.data);
  //
  // LightGBM approach:
  // const booster = lgb.Booster.load(modelPath);
  // return booster.predict(featureVectors);
  
  throw new Error(
    '[Model Inference] Model inference engine not configured. ' +
    'Please install and configure ONNX Runtime or LightGBM Node.js bindings. ' +
    'Falling back to heuristic ranking.'
  );
}

/**
 * Compute fallback heuristic scores when model is unavailable.
 * 
 * Heuristic: score = -sqrt(sum(macro_delta^2))
 * 
 * Rationale:
 * - Euclidean distance in macro space measures "fit quality"
 * - Smaller distance = better fit (meal closely matches remaining needs)
 * - Negative sign ensures higher scores = better (for consistent sorting)
 * - sqrt prevents large macro deltas from dominating
 * 
 * Example:
 * - Meal A: deltas = [20, 2, 2, 1] → score = -√(400+4+4+1) = -√409 = -20.2
 * - Meal B: deltas = [300, 20, 20, 10] → score = -√(90000+400+400+100) = -√90900 = -301.5
 * - Meal A scores higher (better fit)
 * 
 * This provides a reasonable ranking without ML model, ensuring service continuity.
 * 
 * @param meals - Array of meal objects
 * @param remaining - User's remaining macros
 * @returns Array of heuristic scores (one per meal)
 */
export function fallbackHeuristicRanking(meals: Meal[], remaining: RemainingMacros): number[] {
  const scores: number[] = [];
  
  for (const meal of meals) {
    // Compute macro deltas (same as features 1-4)
    const deltaCalories = Math.abs(meal.calories - remaining.calories);
    const deltaProtein = Math.abs(meal.protein_g - remaining.protein_g);
    const deltaCarbs = Math.abs(meal.carbs_g - remaining.carbs_g);
    const deltaFat = Math.abs(meal.fat_g - remaining.fat_g);
    
    // Compute Euclidean distance
    const sumSquares = 
      deltaCalories * deltaCalories +
      deltaProtein * deltaProtein +
      deltaCarbs * deltaCarbs +
      deltaFat * deltaFat;
    
    // Negative sqrt for "higher is better" scoring
    const score = -Math.sqrt(sumSquares);
    
    scores.push(score);
  }
  
  return scores;
}

/**
 * Sort meals by predicted scores in descending order.
 * 
 * Creates pairs of (meal, score) and sorts by score descending (highest first).
 * Returns sorted meals array.
 * 
 * @param meals - Array of meal objects
 * @param scores - Array of predicted scores (parallel to meals array)
 * @returns Array of meals sorted by score descending
 */
export function sortMealsByScore(meals: Meal[], scores: number[]): Meal[] {
  // Validate inputs
  if (meals.length !== scores.length) {
    throw new Error(
      `[Ranking] Array length mismatch: ${meals.length} meals, ${scores.length} scores`
    );
  }
  
  // Create (meal, score) pairs
  const mealScorePairs: Array<{ meal: Meal; score: number }> = [];
  for (let i = 0; i < meals.length; i++) {
    mealScorePairs.push({
      meal: meals[i],
      score: scores[i]
    });
  }
  
  // Sort by score descending (highest first)
  mealScorePairs.sort((a, b) => b.score - a.score);
  
  // Extract sorted meals
  return mealScorePairs.map(pair => pair.meal);
}

/**
 * Select top meals with randomization for variety.
 * 
 * Instead of always returning the exact same top N meals, this function:
 * 1. Takes the top 20 highest-scored meals (if available)
 * 2. Randomly shuffles them
 * 3. Returns the first N meals from the shuffled list
 * 
 * This ensures variety across multiple plan generations while still
 * prioritizing well-scored meals.
 * 
 * @param rankedMeals - Array of meals sorted by score descending
 * @param count - Number of meals to select (default: 5)
 * @returns Array of randomly selected top meals
 */
export function selectTopWithVariety(rankedMeals: Meal[], count: number = 5): Meal[] {
  if (rankedMeals.length === 0) return [];
  
  // If we have fewer meals than requested, return all
  if (rankedMeals.length <= count) return rankedMeals;
  
  // Take top 20 meals (or all if less than 20) as the "good quality" pool
  const poolSize = Math.min(20, rankedMeals.length);
  const topPool = rankedMeals.slice(0, poolSize);
  
  // Shuffle the pool for randomization
  const shuffled = [...topPool];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  
  // Return the requested count from shuffled pool
  return shuffled.slice(0, count);
}

/**
 * Main meal ranking function with model inference and fallback.
 * 
 * This is the primary entry point for meal ranking. It:
 * 1. Computes features for all candidate meals
 * 2. Attempts model inference
 * 3. Falls back to heuristic if model fails
 * 4. Ranks meals by score
 * 5. Returns top 5
 * 
 * Error handling strategy:
 * - Try model inference first
 * - On any error, log warning and use heuristic fallback
 * - Never throw errors (ensures service availability)
 * 
 * @param profile - User profile with cuisine preference
 * @param meals - Array of candidate meals to rank
 * @param remaining - User's remaining macros
 * @param userId - User ID for recency calculation
 * @param requestedSlot - Meal slot being requested
 * @param supabase - Supabase client for database queries
 * @returns Promise<Meal[]> - Top 5 ranked meals
 */
export async function rankAndSelectTop5(
  profile: UserProfile,
  meals: Meal[],
  remaining: RemainingMacros,
  userId: string,
  requestedSlot: string,
  supabase: any
): Promise<Meal[]> {
  try {
    // Handle empty candidate list
    if (!meals || meals.length === 0) {
      console.warn('[Ranking] No candidate meals provided');
      return [];
    }
    
    // Compute features for all candidate meals
    console.log(`[Ranking] Computing features for ${meals.length} candidate meals`);
    const featureVectors: number[][] = [];
    
    for (const meal of meals) {
      try {
        const features = await computeFeatures(
          profile,
          meal,
          remaining,
          userId,
          requestedSlot,
          supabase
        );
        
        // Validate feature vector
        if (!validateFeatureVector(features, modelState.schema)) {
          console.error(`[Ranking] Invalid feature vector for meal ${meal.id}, skipping`);
          continue;
        }
        
        featureVectors.push(features);
      } catch (error) {
        console.error(`[Ranking] Error computing features for meal ${meal.id}:`, error);
        // Skip this meal, continue with others
      }
    }
    
    if (featureVectors.length === 0) {
      console.error('[Ranking] No valid feature vectors computed');
      return [];
    }
    
    // Filter meals to only those with valid features
    const validMeals = meals.slice(0, featureVectors.length);
    
    let scores: number[];
    let usedFallback = false;
    
    // Attempt ML ranking via Railway, fall back to heuristic on error
    try {
      console.log('[Ranking] Calling Railway ML service for ranking');
      
      // Import Railway client
      const { rankMealsWithML } = await import('@/lib/meal-recommender/railway-client');
      
      // Prepare candidates for Railway API
      const candidates = validMeals.map((meal, index) => ({
        meal_id: meal.id,
        meal_name: meal.name,
        features: featureVectors[index]
      }));
      
      // Call Railway ranking service
      const rankedResults = await rankMealsWithML(candidates);
      
      // Extract scores (already sorted by Railway, but we need scores array)
      scores = rankedResults.map(r => r.score);
      
      console.log('[Ranking] Railway ML ranking successful');
    } catch (error) {
      // Railway failed, use fallback heuristic
      console.warn(
        '[Ranking] Railway ML service failed, falling back to heuristic ranking:',
        error instanceof Error ? error.message : error
      );
      usedFallback = true;
      
      scores = fallbackHeuristicRanking(validMeals, remaining);
      console.log('[Ranking] Fallback heuristic ranking complete');
    }
    
    // Rank meals by score
    const rankedMeals = sortMealsByScore(validMeals, scores);
    
    // Select top meals with randomization for variety
    const topMeals = selectTopWithVariety(rankedMeals, 5);
    
    console.log(
      `[Ranking] Ranked ${validMeals.length} meals, returning ${topMeals.length} with variety` +
      (usedFallback ? ' (using fallback heuristic)' : ' (using trained model)')
    );
    
    return topMeals;
  } catch (error) {
    console.error('[Ranking] Unexpected error in rankAndSelectTop5:', error);
    // Return empty array rather than crashing
    return [];
  }
}

// =============================================================================
// Public API for Integration with Existing Code
// =============================================================================

/**
 * MealSuggestion type matching the existing API contract
 */
interface MealSuggestion {
  meal_type: string;
  meal_name: string;
  description: string;
  items: string[];
  calories: number;
  protein_g: number;
  carbs_g: number;
  fat_g: number;
}

/**
 * ProfileContext type matching the existing meal plan API
 */
interface ProfileContext {
  age: number;
  gender: string;
  bmi: number;
  bmi_category: string;
  activity_level: string;
  goal: string;
  target_calories: number;
  target_protein_g: number;
  target_carbs_g: number;
  target_fat_g: number;
  cuisine_preference?: string | null;
}

/**
 * Main entry point for LightGBM meal ranking - replaces LLM call
 * 
 * This function is the drop-in replacement for the Groq API call in generateMealPlanForUser.
 * It maintains the same interface contract to ensure zero-disruption migration.
 * 
 * Flow:
 * 1. Import Supabase client for database queries
 * 2. Fetch candidate meals from meals table filtered by meal slot
 * 3. Engineer features for all candidates
 * 4. Run model inference (or fallback heuristic)
 * 5. Rank meals and select top 5
 * 6. Map Meal objects to MealSuggestion format
 * 7. Return array matching existing API contract
 * 
 * Requirements Mapping:
 * - Requirement 7: Replace LLM call while preserving function signature
 * - Requirement 6: Rank meals and return top 5 in expected format
 * - Requirement 5: Real-time feature engineering for inference
 * - Requirement 13: Graceful fallback if model fails
 * 
 * @param userId - User ID for fetching profile and meal logs
 * @param mealType - Requested meal slot (breakfast/lunch/dinner/snack) or undefined for any
 * @param profileData - User's nutrition profile with preferences
 * @param remainingMacros - User's remaining macros for today
 * @returns Promise<MealSuggestion[]> - Top 5 meal recommendations
 */
export async function rankMeals(
  userId: string,
  mealType: string | undefined,
  profileData: ProfileContext,
  remainingMacros: RemainingMacros
): Promise<MealSuggestion[]> {
  try {
    console.log(`[rankMeals] Starting meal ranking for user ${userId}, meal type: ${mealType || 'any'}`);
    console.log(`[rankMeals] Full profile data:`, profileData);
    console.log(`[rankMeals] Profile cuisine_preference:`, profileData.cuisine_preference);
    console.log(`[rankMeals] Profile has cuisine_preference key:`, 'cuisine_preference' in profileData);
    
    // Import Supabase client
    const { createServerClient } = await import('@/lib/supabase/server');
    const supabase = createServerClient();
    
    // Fetch candidate meals from meals table
    // Filter by meal_slot if mealType is specified
    // Filter by cuisine_type if user has a cuisine preference
    let query = supabase
      .from('meals')
      .select('*');
    
    if (mealType) {
      query = query.eq('meal_slot', mealType);
    }
    
    // HARD FILTER: Only show meals matching user's cuisine preference if set
    if (profileData.cuisine_preference) {
      query = query.eq('cuisine_type', profileData.cuisine_preference);
      console.log(`[rankMeals] Filtering meals by cuisine: ${profileData.cuisine_preference}`);
    }
    
    const { data: candidateMeals, error: mealsError } = await query;
    
    if (mealsError) {
      console.error('[rankMeals] Error fetching candidate meals:', mealsError);
      return [];
    }
    
    if (!candidateMeals || candidateMeals.length === 0) {
      console.warn('[rankMeals] No candidate meals found');
      return [];
    }
    
    console.log(`[rankMeals] Found ${candidateMeals.length} candidate meals`);
    
    // Map database meals to Meal type for ranking
    const meals: Meal[] = candidateMeals.map((dbMeal: any) => ({
      id: dbMeal.id,
      name: dbMeal.name,
      description: dbMeal.description,
      cuisine_type: dbMeal.cuisine_type || '',
      meal_slot: dbMeal.meal_slot || '',
      calories: dbMeal.calories || 0,
      protein_g: dbMeal.protein_g || 0,
      carbs_g: dbMeal.carbs_g || 0,
      fat_g: dbMeal.fat_g || 0,
      ingredients: dbMeal.ingredients || []
    }));
    
    // Prepare user profile for feature engineering
    const userProfile: UserProfile = {
      cuisine_preference: profileData.cuisine_preference || null
    };
    
    // Rank meals using the trained model or fallback heuristic
    const requestedSlot = mealType || 'any';
    const rankedMeals = await rankAndSelectTop5(
      userProfile,
      meals,
      remainingMacros,
      userId,
      requestedSlot,
      supabase
    );
    
    // Map ranked Meal objects to MealSuggestion format
    const mealSuggestions: MealSuggestion[] = rankedMeals.map((meal: Meal) => ({
      meal_type: meal.meal_slot,
      meal_name: meal.name,
      description: meal.description || '',
      items: meal.ingredients || [],
      calories: Math.round(meal.calories),
      protein_g: Math.round(meal.protein_g),
      carbs_g: Math.round(meal.carbs_g),
      fat_g: Math.round(meal.fat_g)
    }));
    
    console.log(`[rankMeals] Returning ${mealSuggestions.length} meal recommendations`);
    
    // Log recommendation event (fire-and-forget, non-blocking)
    // This captures recommendation context for future model retraining
    if (rankedMeals.length > 0) {
      const { logRecommendation } = await import('@/lib/meal-recommender/logger');
      const mealIds = rankedMeals.map(m => m.id);
      logRecommendation(userId, mealIds, requestedSlot, profileData, remainingMacros);
    }
    
    return mealSuggestions;
    
  } catch (error) {
    console.error('[rankMeals] Unexpected error:', error);
    // Return empty array to maintain service availability
    // Caller can handle empty results gracefully
    return [];
  }
}
