/**
 * Recommendation Event Logger for LightGBM Meal Ranker
 * 
 * Purpose:
 *     This module logs meal recommendation events and user responses to enable
 *     future model retraining on production feedback data.
 * 
 * Key Responsibilities:
 *     - Log recommendation events when meals are suggested to users
 *     - Capture context: user_id, recommended_meal_ids, requested_meal_slot,
 *       user_profile_snapshot, remaining_macros_snapshot, timestamp
 *     - Update events with user outcomes:
 *         * 'accepted': User logged a recommended meal
 *         * 'rejected_logged_other': User logged a meal not in recommendations
 *         * NULL: User dismissed recommendations (implicit rejection)
 *     - Implement fire-and-forget logging pattern (non-blocking)
 *     - Handle logging failures gracefully without affecting recommendations
 * 
 * Fire-and-Forget Pattern:
 *     This module uses a fire-and-forget pattern for all database operations.
 *     This means:
 *     - Functions are called WITHOUT await (caller doesn't wait for completion)
 *     - All errors are caught and logged internally (never thrown)
 *     - Logging failures never block or delay recommendation responses
 *     - Database operations happen asynchronously in the background
 * 
 *     Example:
 *       // CORRECT: Fire-and-forget (no await)
 *       logRecommendation(userId, mealIds, slot, profile, remaining);
 *       
 *       // WRONG: Awaiting defeats the purpose
 *       await logRecommendation(userId, mealIds, slot, profile, remaining);
 * 
 *     Rationale:
 *       - Recommendation latency is critical for user experience
 *       - Event logging is important but not urgent (can happen in background)
 *       - Failed logs should not cause recommendation failures
 *       - This pattern decouples logging from the critical path
 * 
 * Dependencies:
 *     - @supabase/supabase-js: For database inserts/updates
 * 
 * Expected Input:
 *     - Recommendation context (user, meals, slot, profile, macros)
 *     - User outcome updates (accepted meal ID or rejection signal)
 * 
 * Expected Output:
 *     - Rows inserted/updated in meal_recommendation_events table
 * 
 * Database Schema:
 *     meal_recommendation_events {
 *       id: UUID (primary key)
 *       user_id: TEXT (foreign key to users)
 *       recommended_meal_ids: TEXT[] (array of meal IDs shown)
 *       requested_meal_slot: TEXT (breakfast/lunch/dinner/snack)
 *       user_profile_snapshot: JSONB (user profile at recommendation time)
 *       remaining_macros_snapshot: JSONB (remaining macros at recommendation time)
 *       timestamp: TIMESTAMPTZ (when recommendation was made)
 *       outcome: TEXT nullable (accepted/rejected_logged_other/NULL)
 *       accepted_meal_id: TEXT nullable (which meal was accepted, if any)
 *     }
 * 
 * Usage:
 *     import { logRecommendation, updateOutcome } from '@/lib/meal-recommender/logger';
 *     
 *     // When generating recommendations (no await!)
 *     logRecommendation(userId, mealIds, slot, profile, remaining);
 *     
 *     // When user logs a meal (no await!)
 *     updateOutcome(userId, mealId, 'accepted');
 * 
 * Author: Generated by Kiro AI
 * Date: 2024
 */

import { createServerClient } from '@/lib/supabase/server';

/**
 * Type definitions for recommendation event logging
 */

interface RemainingMacros {
  calories: number;
  protein_g: number;
  carbs_g: number;
  fat_g: number;
}

interface UserProfileSnapshot {
  age?: number;
  gender?: string;
  bmi?: number;
  bmi_category?: string;
  activity_level?: string;
  goal?: string;
  target_calories?: number;
  target_protein_g?: number;
  target_carbs_g?: number;
  target_fat_g?: number;
  cuisine_preference?: string | null;
}

type Outcome = 'accepted' | 'rejected_logged_other';

/**
 * Log a recommendation event to the database (fire-and-forget).
 * 
 * This function creates a new event record in meal_recommendation_events table
 * capturing the recommendation context for future model retraining.
 * 
 * IMPORTANT: This function uses fire-and-forget pattern.
 * - Call WITHOUT await
 * - All errors are caught and logged internally
 * - Never throws exceptions
 * - Never blocks the caller
 * 
 * Event Structure:
 * - user_id: Who received the recommendations
 * - recommended_meal_ids: Array of meal IDs shown (typically top 5)
 * - requested_meal_slot: Meal type requested (breakfast/lunch/dinner/snack)
 * - user_profile_snapshot: Complete user profile at recommendation time
 * - remaining_macros_snapshot: Remaining macros at recommendation time
 * - timestamp: When recommendations were generated (auto-set by DB)
 * - outcome: NULL initially (will be updated if user logs a meal)
 * - accepted_meal_id: NULL initially (will be updated if user logs a meal)
 * 
 * Rationale for Snapshots:
 * - User profiles and remaining macros change over time
 * - For model retraining, we need the EXACT context when recommendation was made
 * - Snapshots preserve historical context for accurate feature engineering
 * 
 * Example:
 *   const profile = { age: 30, goal: 'lose', target_calories: 2000, ... };
 *   const remaining = { calories: 500, protein_g: 30, carbs_g: 40, fat_g: 15 };
 *   const mealIds = ['meal_1', 'meal_2', 'meal_3', 'meal_4', 'meal_5'];
 *   
 *   // Fire-and-forget: no await, no error handling needed
 *   logRecommendation('user_123', mealIds, 'lunch', profile, remaining);
 * 
 * @param userId - User ID who received recommendations
 * @param mealIds - Array of meal IDs that were recommended (top 5)
 * @param slot - Meal slot requested (breakfast/lunch/dinner/snack)
 * @param profile - User profile snapshot at recommendation time
 * @param remaining - Remaining macros snapshot at recommendation time
 */
export function logRecommendation(
  userId: string,
  mealIds: string[],
  slot: string,
  profile: UserProfileSnapshot,
  remaining: RemainingMacros
): void {
  // Fire-and-forget: async operation without awaiting
  (async () => {
    try {
      console.log(`[Recommendation Logger] Logging recommendation for user ${userId}, slot ${slot}`);
      
      // Create Supabase client
      const supabase = createServerClient();
      
      // Check if user_id is a valid UUID format
      // If it's an email (like from nutrition_profiles), skip logging
      // This table expects UUID from auth.users, not email strings
      const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
      if (!uuidRegex.test(userId)) {
        console.log(
          `[Recommendation Logger] Skipping log for non-UUID user_id: ${userId} ` +
          `(table expects UUID, got email/string)`
        );
        return;
      }
      
      // Insert event record
      const { error } = await supabase
        .from('meal_recommendation_events')
        .insert({
          user_id: userId,
          recommended_meal_ids: mealIds,
          requested_meal_slot: slot,
          user_profile_snapshot: profile as any, // JSONB
          remaining_macros_snapshot: remaining as any, // JSONB
          // timestamp is auto-set by DB default (NOW())
          // outcome is NULL initially
          // accepted_meal_id is NULL initially
        });
      
      if (error) {
        console.error(
          '[Recommendation Logger] Failed to log recommendation event:',
          error.message
        );
        // Don't throw - this is fire-and-forget
        return;
      }
      
      console.log(
        `[Recommendation Logger] Successfully logged recommendation for user ${userId} ` +
        `(${mealIds.length} meals, slot: ${slot})`
      );
    } catch (error) {
      // Catch any unexpected errors
      console.error(
        '[Recommendation Logger] Unexpected error in logRecommendation:',
        error instanceof Error ? error.message : error
      );
      // Don't throw - this is fire-and-forget
    }
  })();
}

/**
 * Update the outcome of the most recent recommendation event for a user (fire-and-forget).
 * 
 * This function updates the most recent event record when a user logs a meal,
 * indicating whether they accepted a recommendation or logged something else.
 * 
 * IMPORTANT: This function uses fire-and-forget pattern.
 * - Call WITHOUT await
 * - All errors are caught and logged internally
 * - Never throws exceptions
 * - Never blocks the caller
 * 
 * Update Logic:
 * 1. Find the most recent recommendation event for this user (by timestamp)
 * 2. Check if the logged meal ID is in the recommended_meal_ids array
 * 3. If YES: Set outcome='accepted', accepted_meal_id=mealId
 * 4. If NO: Set outcome='rejected_logged_other', accepted_meal_id=NULL
 * 
 * Rationale:
 * - We update the MOST RECENT event because that's the context in which the user made their decision
 * - Outcome tracking enables model retraining on actual user behavior
 * - 'accepted' = user chose one of our recommendations (positive signal)
 * - 'rejected_logged_other' = user ignored our recommendations (negative signal)
 * - NULL outcome = user didn't log anything yet (implicit rejection, tracked separately)
 * 
 * Example Scenarios:
 * 
 * Scenario 1: User accepts a recommendation
 *   - System recommends: ['meal_1', 'meal_2', 'meal_3', 'meal_4', 'meal_5']
 *   - User logs: 'meal_2'
 *   - Update: outcome='accepted', accepted_meal_id='meal_2'
 * 
 * Scenario 2: User logs something else
 *   - System recommends: ['meal_1', 'meal_2', 'meal_3', 'meal_4', 'meal_5']
 *   - User logs: 'meal_99'
 *   - Update: outcome='rejected_logged_other', accepted_meal_id=NULL
 * 
 * Example:
 *   // User logged a meal (fire-and-forget: no await)
 *   updateOutcome('user_123', 'meal_2', 'accepted');
 * 
 * @param userId - User ID who logged the meal
 * @param mealId - Meal ID that was logged
 * @param outcome - Outcome type: 'accepted' or 'rejected_logged_other'
 */
export function updateOutcome(
  userId: string,
  mealId: string,
  outcome: Outcome
): void {
  // Fire-and-forget: async operation without awaiting
  (async () => {
    try {
      console.log(`[Recommendation Logger] Updating outcome for user ${userId}, meal ${mealId}, outcome ${outcome}`);
      
      // Create Supabase client
      const supabase = createServerClient();
      
      // Check if user_id is a valid UUID format
      const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
      if (!uuidRegex.test(userId)) {
        console.log(
          `[Recommendation Logger] Skipping outcome update for non-UUID user_id: ${userId}`
        );
        return;
      }
      
      // Find the most recent recommendation event for this user
      const { data: recentEvent, error: fetchError } = await supabase
        .from('meal_recommendation_events')
        .select('id, recommended_meal_ids')
        .eq('user_id', userId)
        .order('timestamp', { ascending: false })
        .limit(1)
        .single();
      
      if (fetchError) {
        // User may not have any recommendation events yet
        console.warn(
          '[Recommendation Logger] No recent recommendation event found for user:',
          userId,
          fetchError.message
        );
        // Don't throw - this is fire-and-forget
        return;
      }
      
      if (!recentEvent) {
        console.warn(
          '[Recommendation Logger] No recommendation events found for user:',
          userId
        );
        // Don't throw - this is fire-and-forget
        return;
      }
      
      // Update the event with the outcome
      const { error: updateError } = await supabase
        .from('meal_recommendation_events')
        .update({
          outcome: outcome,
          accepted_meal_id: outcome === 'accepted' ? mealId : null,
        })
        .eq('id', recentEvent.id);
      
      if (updateError) {
        console.error(
          '[Recommendation Logger] Failed to update outcome:',
          updateError.message
        );
        // Don't throw - this is fire-and-forget
        return;
      }
      
      console.log(
        `[Recommendation Logger] Successfully updated outcome for user ${userId} ` +
        `(event: ${recentEvent.id}, outcome: ${outcome})`
      );
    } catch (error) {
      // Catch any unexpected errors
      console.error(
        '[Recommendation Logger] Unexpected error in updateOutcome:',
        error instanceof Error ? error.message : error
      );
      // Don't throw - this is fire-and-forget
    }
  })();
}
